version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "Pyker"
    ignore:
      - dependency-name: 'org.apache.maven.plugins:maven-shade-plugin'
        versions:
          - '3.3.0' # Broken, see https://issues.apache.org/jira/browse/MSHADE-417
